"use client";

import { ArrowLeft, BadgeCheck, BarChart3, Bell, Boxes, Building2, Check, ChevronDown, Eye, Flag, LayoutDashboard, MessageSquareText, MoreHorizontal, Search, ShieldCheck, Sparkles, Store, TrendingUp, UserPlus, Users, XCircle } from "lucide-react";
import { useState } from "react";

const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

const seedRows = [
  { id: 1, title: "EMD 645E3B Power Assembly", vendor: "Midwest Rail Systems", status: "Active", flagged: false, views: 782 },
  { id: 2, title: "GE 7FDL16 Prime Mover", vendor: "Gulf Coast Locomotive", status: "Active", flagged: false, views: 644 },
  { id: 3, title: "GE 752 Traction Motor", vendor: "Southern Traction & Electric", status: "Review", flagged: true, views: 506 },
  { id: 4, title: "EMD 710 Turbocharger Rotor", vendor: "Northline Components", status: "Paused", flagged: false, views: 311 },
];

export default function AdminDashboard() {
  const [rows, setRows] = useState(seedRows);
  const [notice, setNotice] = useState("");

  function update(id: number, status: string, message: string) {
    setRows((items) => items.map((item) => item.id === id ? { ...item, status, flagged: false } : item));
    setNotice(message);
    window.setTimeout(() => setNotice(""), 2400);
  }

  return <main className="admin-shell">
    <aside className="admin-sidebar"><a className="brand admin-brand" href={`${BASE_PATH}/`}><span className="brand-mark">LT</span><span className="brand-copy">Locomotive<span>Trader</span></span></a><div className="admin-label">Marketplace admin</div><nav className="dash-nav"><small>Manage</small><a className="active" href="#overview"><LayoutDashboard size={18}/> Overview</a><a href="#listings"><Boxes size={18}/> Listings <b>3,280</b></a><a href="#vendors"><Store size={18}/> Vendors <b>84</b></a><a href="#leads"><MessageSquareText size={18}/> Leads</a><small>Operations</small><a href="#analytics"><BarChart3 size={18}/> Analytics</a><a href="#flags"><Flag size={18}/> Review queue <b className="alert-count">1</b></a><a href="#team"><Users size={18}/> Admin team</a></nav><a className="back-market" href={`${BASE_PATH}/`}><ArrowLeft size={16}/> Back to marketplace</a></aside>
    <div className="admin-main"><header className="dash-header"><div className="dash-search"><Search size={17}/><input placeholder="Search listings, vendors, or leads" /></div><div className="dash-header-actions"><button type="button"><Bell size={19}/><i/></button><div className="avatar dark">KA</div><span><strong>Kyle Admin</strong><small>Marketplace owner</small></span></div></header>
      <div className="dashboard-content" id="overview"><div className="dash-welcome"><div><div className="eyebrow"><span/> Admin operations</div><h1>Marketplace pulse</h1><p>Supply, vendor health, and buyer demand at a glance.</p></div><button className="button button-dark"><UserPlus size={16}/> Invite vendor</button></div>
        <div className="stat-grid admin-stats"><article><span className="stat-icon orange"><Boxes size={20}/></span><div><small>Active listings</small><strong>3,280</strong><em><TrendingUp size={13}/> 12.8%</em></div><p>+372 this month</p></article><article><span className="stat-icon blue"><Store size={20}/></span><div><small>Paying vendors</small><strong>84</strong><em><TrendingUp size={13}/> 6.3%</em></div><p>7 in free trial</p></article><article><span className="stat-icon green"><MessageSquareText size={20}/></span><div><small>Qualified leads</small><strong>618</strong><em><TrendingUp size={13}/> 21.7%</em></div><p>Last 30 days</p></article><article><span className="stat-icon purple"><Eye size={20}/></span><div><small>Buyer visits</small><strong>18.4k</strong><em><TrendingUp size={13}/> 16.2%</em></div><p>66% from search</p></article></div>
        <div className="admin-grid"><section className="panel admin-chart" id="analytics"><div className="panel-head"><div><strong>Marketplace activity</strong><span>Listings viewed and vendor inquiries</span></div><button>Last 30 days <ChevronDown size={14}/></button></div><div className="legend"><span><i className="orange-dot"/> Listing views</span><span><i className="navy-dot"/> Buyer inquiries</span></div><div className="admin-bars">{[42,61,54,69,73,67,82,76,88,91,84,96].map((n,i)=><div key={i}><i style={{height:`${n}%`}}/><b style={{height:`${Math.max(15,n-48)}%`}}/></div>)}</div><div className="chart-labels"><span>Jul 8</span><span>Jul 15</span><span>Jul 22</span><span>Jul 29</span><span>Aug 8</span></div></section><section className="panel health-panel"><div className="panel-head"><div><strong>Vendor health</strong><span>Subscription and response quality</span></div></div><div className="health-score"><div><strong>91</strong><span>/100</span></div><p><b>Healthy marketplace</b><small>Vendor response quality is above target.</small></p></div><div className="health-row"><span>Active subscription rate</span><strong>96%</strong><i><b style={{width:"96%"}}/></i></div><div className="health-row"><span>30-day vendor retention</span><strong>94%</strong><i><b style={{width:"94%"}}/></i></div><div className="health-row"><span>Replies within 24 hours</span><strong>87%</strong><i><b style={{width:"87%"}}/></i></div></section></div>
        <section className="panel moderation-panel" id="listings"><div className="panel-head inventory-head"><div><strong>Listing moderation</strong><span>Review, feature, pause, or restore marketplace inventory.</span></div><div><label className="table-search"><Search size={15}/><input placeholder="Search listings"/></label><button className="button button-outline button-small">All statuses <ChevronDown size={14}/></button></div></div><div className="listing-table admin-table"><div className="table-row table-labels"><span>Listing</span><span>Vendor</span><span>Status</span><span>Views</span><span>Actions</span></div>{rows.map(row=><div className="table-row" key={row.id}><div className="admin-title"><strong>{row.title}</strong>{row.flagged&&<em><Flag size={12}/> Needs review</em>}</div><div className="admin-vendor"><span>{row.vendor}</span><BadgeCheck size={15}/></div><span><b className={`status ${row.status.toLowerCase()}`}>{row.status}</b></span><span className="metric-cell"><strong>{row.views}</strong><small>total</small></span><div className="row-actions">{row.status==="Review"?<><button className="action-text approve" onClick={()=>update(row.id,"Active","Listing approved and restored to search.")}><Check size={14}/> Approve</button><button className="action-text reject" onClick={()=>update(row.id,"Deleted","Listing removed from the marketplace.")}><XCircle size={14}/> Remove</button></>:<><button title="Feature listing" onClick={()=>setNotice("Listing featured for seven days.")}><Sparkles size={16}/></button><button title="Verify vendor"><ShieldCheck size={16}/></button><button title="More options"><MoreHorizontal size={17}/></button></>}</div></div>)}</div></section>
        <section className="admin-vendors" id="vendors"><div className="section-heading split-heading"><div><div className="eyebrow"><span/> Vendor accounts</div><h2>Recent vendor activity</h2></div><button className="arrow-link">Manage all vendors →</button></div><div className="admin-vendor-grid"><article><div className="vendor-logo">MR</div><div><strong>Midwest Rail Systems</strong><span><BadgeCheck size={14}/> Growth · Active</span></div><small>142 listings</small></article><article><div className="vendor-logo">GC</div><div><strong>Gulf Coast Locomotive</strong><span><BadgeCheck size={14}/> Network · Active</span></div><small>208 listings</small></article><article><div className="vendor-logo">ST</div><div><strong>Southern Traction & Electric</strong><span><BadgeCheck size={14}/> Trial · 18 days left</span></div><small>86 listings</small></article></div></section>
      </div>
    </div>{notice&&<div className="toast"><Check size={17}/>{notice}</div>}
  </main>;
}
