export type Listing = {
  id: number;
  title: string;
  category: string;
  subcategory: string;
  manufacturer: string;
  builder: string;
  condition: string;
  region: string;
  location: string;
  quantity: number;
  partNumber: string;
  models: string[];
  engineFamily: string;
  application: string;
  availability: "In stock" | "Core exchange" | "Lead time" | "Made to order";
  leadTime: string;
  vendor: string;
  vendorSince: string;
  image: string;
  featured?: boolean;
  posted: string;
  ageDays: number;
  description: string;
  keywords: string[];
};

export const listings: Listing[] = [
  {
    id: 1,
    title: "EMD 645E3B Power Assembly",
    category: "Engine Components",
    subcategory: "Power assemblies",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Remanufactured",
    region: "United States",
    location: "Chicago, Illinois",
    quantity: 4,
    partNumber: "645E3B-PA",
    models: ["GP38", "GP40", "SD40-2"],
    engineFamily: "EMD 645E3",
    application: "Cylinder power assembly",
    availability: "Core exchange",
    leadTime: "Exchange stock available",
    vendor: "Midwest Rail Systems",
    vendorSince: "Verified since 2019",
    image: "/listings/power-assembly.jpg",
    featured: true,
    posted: "2 hours ago",
    ageDays: 0,
    description: "Remanufactured 645E3B cylinder power assembly supplied with inspection documentation. Configuration and core eligibility are confirmed against the engine build before shipment.",
    keywords: ["piston", "liner", "head", "fork rod", "blade rod", "power pack", "exchange"],
  },
  {
    id: 2,
    title: "GE 7FDL16 Prime Mover",
    category: "Engines",
    subcategory: "Complete engines",
    manufacturer: "Wabtec / GE",
    builder: "GE",
    condition: "Rebuildable Core",
    region: "United States",
    location: "Houston, Texas",
    quantity: 2,
    partNumber: "7FDL16-CORE",
    models: ["C40-8", "C44-9W", "AC4400CW"],
    engineFamily: "GE 7FDL16",
    application: "Prime mover",
    availability: "In stock",
    leadTime: "Ready for inspection",
    vendor: "Gulf Coast Locomotive",
    vendorSince: "Verified since 2016",
    image: "/listings/prime-mover.jpg",
    featured: true,
    posted: "Yesterday",
    ageDays: 1,
    description: "Complete take-out 7FDL16 prime movers offered as rebuildable cores. Units are stored indoors and can be prepared for domestic shipment or export.",
    keywords: ["FDL", "diesel engine", "long block", "take-out", "core", "Dash 8", "Dash 9"],
  },
  {
    id: 3,
    title: "GE 752AH DC Traction Motor",
    category: "Traction Motors",
    subcategory: "DC traction motors",
    manufacturer: "Wabtec / GE",
    builder: "GE",
    condition: "Rebuilt",
    region: "United States",
    location: "Birmingham, Alabama",
    quantity: 6,
    partNumber: "GE-752AH",
    models: ["C40-8", "C44-9W", "Dash 8 / 9"],
    engineFamily: "Not applicable",
    application: "Axle-mounted traction",
    availability: "In stock",
    leadTime: "Ready to ship",
    vendor: "Southern Traction & Electric",
    vendorSince: "Verified since 2021",
    image: "/listings/traction-motor.jpg",
    posted: "2 days ago",
    ageDays: 2,
    description: "Rebuilt 752AH-family DC traction motor with renewed bearings, electrical test records, and documented pinion configuration. Gear ratio must be matched to the receiving locomotive.",
    keywords: ["752", "DC motor", "armature", "axle hung", "pinion", "Dash 8", "Dash 9"],
  },
  {
    id: 4,
    title: "EMD 710 Turbocharger Rotor Assembly",
    category: "Turbochargers",
    subcategory: "Turbo rotating groups",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "New Surplus",
    region: "Canada",
    location: "Calgary, Alberta",
    quantity: 8,
    partNumber: "EMD-710-ROTOR",
    models: ["SD70", "SD75", "GP60"],
    engineFamily: "EMD 710G",
    application: "Turbocharger rotating assembly",
    availability: "In stock",
    leadTime: "Ready to ship",
    vendor: "Northline Components",
    vendorSince: "Verified since 2018",
    image: "/listings/turbocharger.jpg",
    posted: "3 days ago",
    ageDays: 3,
    description: "Unused surplus rotating assemblies for EMD 710-family turbochargers. Final fitment is verified by turbocharger model, gear-train arrangement, and engine build.",
    keywords: ["710", "turbo", "rotor", "turbine", "compressor wheel", "rotating group"],
  },
  {
    id: 5,
    title: "EMD 645 Cylinder Heads — Lot of 12",
    category: "Engine Components",
    subcategory: "Cylinder heads",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Remanufactured",
    region: "United States",
    location: "Altoona, Pennsylvania",
    quantity: 24,
    partNumber: "EMD-645-HEAD",
    models: ["GP38", "GP40", "SD40"],
    engineFamily: "EMD 645E / E3",
    application: "Cylinder head",
    availability: "In stock",
    leadTime: "Ships in 2–3 business days",
    vendor: "Keystone Diesel Works",
    vendorSince: "Verified since 2017",
    image: "/listings/engine-blocks.jpg",
    posted: "4 days ago",
    ageDays: 4,
    description: "Pressure-tested remanufactured cylinder heads with renewed valves, guides, and seats. The listing reference identifies the family; exact interchange is confirmed from engine records.",
    keywords: ["645", "head", "valve", "guide", "seat", "pressure tested", "top deck"],
  },
  {
    id: 6,
    title: "26-C Automatic Brake Valve",
    category: "Air & Brake",
    subcategory: "Brake control valves",
    manufacturer: "New York Air Brake",
    builder: "Multi-platform",
    condition: "New",
    region: "United States",
    location: "Elkhart, Indiana",
    quantity: 12,
    partNumber: "26-C",
    models: ["GP Series", "SD Series", "Legacy road fleet"],
    engineFamily: "Not applicable",
    application: "Automatic train brake control",
    availability: "In stock",
    leadTime: "Ready to ship",
    vendor: "Great Lakes Rail Supply",
    vendorSince: "Verified since 2020",
    image: "/listings/warehouse.jpg",
    posted: "5 days ago",
    ageDays: 5,
    description: "26-C-family automatic brake valve for 26L-equipped locomotive brake stands. Porting, handle arrangement, and locomotive schedule should be verified before installation.",
    keywords: ["26C", "26-L", "automatic brake", "brake stand", "air brake", "NYAB"],
  },

  // Engines — six additional locomotive prime movers and long blocks.
  {
    id: 7,
    title: "EMD 8-710G3A-T3 710ECO Engine",
    category: "Engines",
    subcategory: "Complete engines",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Remanufactured",
    region: "United States",
    location: "Muncie, Indiana",
    quantity: 1,
    partNumber: "8-710G3A-T3",
    models: ["GP20C-ECO", "710ECO repower"],
    engineFamily: "EMD 710G",
    application: "Low-emissions repower",
    availability: "Lead time",
    leadTime: "Build slot: 6–8 weeks",
    vendor: "Heartland Repower Services",
    vendorSince: "Verified since 2018",
    image: "/listings/prime-mover.jpg",
    featured: true,
    posted: "6 days ago",
    ageDays: 6,
    description: "Remanufactured eight-cylinder 710ECO engine configured for repower applications. Controls, cooling package, and installation scope are matched to the donor locomotive.",
    keywords: ["710ECO", "repower", "Tier 3", "eight cylinder", "prime mover", "GP20C"],
  },
  {
    id: 8,
    title: "EMD 12-710G3A-T3 710ECO Engine",
    category: "Engines",
    subcategory: "Complete engines",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Remanufactured",
    region: "United States",
    location: "Tacoma, Washington",
    quantity: 1,
    partNumber: "12-710G3A-T3",
    models: ["SD32ECO", "710ECO repower"],
    engineFamily: "EMD 710G",
    application: "Road-locomotive repower",
    availability: "Made to order",
    leadTime: "Project schedule required",
    vendor: "Cascade Locomotive Works",
    vendorSince: "Verified since 2015",
    image: "/listings/prime-mover.jpg",
    posted: "1 week ago",
    ageDays: 7,
    description: "Twelve-cylinder 710ECO engine package for locomotive modernization programs. Final scope can include the matched alternator, aftercooling, and electronic controls.",
    keywords: ["710ECO", "SD32ECO", "repower", "twelve cylinder", "prime mover", "emissions"],
  },
  {
    id: 9,
    title: "EMD 16-645E3C Engine Core",
    category: "Engines",
    subcategory: "Engine cores",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Rebuildable Core",
    region: "United States",
    location: "Kansas City, Missouri",
    quantity: 3,
    partNumber: "16-645E3C",
    models: ["SD40-2", "SD40T-2", "SD40-3"],
    engineFamily: "EMD 645E3",
    application: "Road locomotive prime mover",
    availability: "In stock",
    leadTime: "Inspection by appointment",
    vendor: "Central States Diesel",
    vendorSince: "Verified since 2014",
    image: "/listings/engine-blocks.jpg",
    posted: "1 week ago",
    ageDays: 8,
    description: "Complete 16-645E3C take-out engines offered as rebuildable cores for SD40-family programs. Serial and crankcase condition reports are available for review.",
    keywords: ["645E3C", "SD40-2", "engine core", "crankcase", "sixteen cylinder", "take-out"],
  },
  {
    id: 10,
    title: "EMD 16-645F3B Engine Core",
    category: "Engines",
    subcategory: "Engine cores",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Rebuildable Core",
    region: "Canada",
    location: "Winnipeg, Manitoba",
    quantity: 2,
    partNumber: "16-645F3B",
    models: ["SD50", "645F rebuild program"],
    engineFamily: "EMD 645F",
    application: "Road locomotive prime mover",
    availability: "In stock",
    leadTime: "Ready for inspection",
    vendor: "Prairie Rail Rebuilders",
    vendorSince: "Verified since 2016",
    image: "/listings/engine-blocks.jpg",
    posted: "9 days ago",
    ageDays: 9,
    description: "Stored 16-645F3B engine cores for SD50-family overhaul or component recovery. Engine serial, storage history, and visible-condition report are supplied with inquiry.",
    keywords: ["645F3B", "SD50", "engine core", "crankcase", "overhaul", "prime mover"],
  },
  {
    id: 11,
    title: "GE 7FDL12 Prime Mover",
    category: "Engines",
    subcategory: "Complete engines",
    manufacturer: "Wabtec / GE",
    builder: "GE",
    condition: "Overhauled",
    region: "Brazil",
    location: "Contagem, Minas Gerais",
    quantity: 2,
    partNumber: "7FDL12",
    models: ["C30-7", "Dash 8-32B", "C30ACi"],
    engineFamily: "GE 7FDL12",
    application: "Prime mover",
    availability: "Core exchange",
    leadTime: "Exchange stock available",
    vendor: "Minas Rail Components",
    vendorSince: "Verified since 2019",
    image: "/listings/prime-mover.jpg",
    featured: true,
    posted: "10 days ago",
    ageDays: 10,
    description: "Overhauled twelve-cylinder 7FDL locomotive engine. Cooling, governor, and accessory configuration are set to the receiving locomotive build sheet.",
    keywords: ["7FDL12", "FDL", "C30-7", "C30ACi", "diesel engine", "prime mover"],
  },
  {
    id: 12,
    title: "GEVO-12 Long Block",
    category: "Engines",
    subcategory: "Long blocks",
    manufacturer: "Wabtec / GE",
    builder: "GE",
    condition: "Remanufactured",
    region: "United States",
    location: "Erie, Pennsylvania",
    quantity: 1,
    partNumber: "GEVO-12-LB",
    models: ["ES44AC", "ES44DC", "ET44AC"],
    engineFamily: "GE Evolution Series",
    application: "Heavy-haul prime mover",
    availability: "Lead time",
    leadTime: "4–6 weeks after build review",
    vendor: "Lake Erie Power Systems",
    vendorSince: "Verified since 2017",
    image: "/listings/prime-mover.jpg",
    posted: "11 days ago",
    ageDays: 11,
    description: "Remanufactured GEVO-12 long block for Evolution Series locomotive overhaul. ET44 applications use the GEVO12-LDD variant and require build-specific confirmation.",
    keywords: ["GEVO12", "GEVO-12", "Evolution Series", "ES44AC", "ET44AC", "long block"],
  },

  // Engine components — eight additional high-demand service items.
  {
    id: 13,
    title: "EMD 645E EconoLife Power Assembly",
    category: "Engine Components",
    subcategory: "Power assemblies",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Remanufactured",
    region: "United States",
    location: "Mayfield, Kentucky",
    quantity: 18,
    partNumber: "645E-ECONOLIFE",
    models: ["GP38", "GP40", "SD40-2"],
    engineFamily: "EMD 645E / E3",
    application: "Cylinder power assembly",
    availability: "Core exchange",
    leadTime: "Exchange stock available",
    vendor: "Bluegrass Engine Exchange",
    vendorSince: "Verified since 2013",
    image: "/listings/power-assembly.jpg",
    posted: "12 days ago",
    ageDays: 12,
    description: "EconoLife-family remanufactured power assemblies for 645E and 645E3 engines, available in fork-rod and blade-rod configurations after build verification.",
    keywords: ["EconoLife", "645E", "645E3", "power assembly", "fork rod", "blade rod", "liner"],
  },
  {
    id: 14,
    title: "EMD 710G Power Assembly",
    category: "Engine Components",
    subcategory: "Power assemblies",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Remanufactured",
    region: "United States",
    location: "Roanoke, Virginia",
    quantity: 10,
    partNumber: "710G-PA",
    models: ["SD70M", "SD70MAC", "SD75"],
    engineFamily: "EMD 710G",
    application: "Cylinder power assembly",
    availability: "Core exchange",
    leadTime: "Ships in 5–7 business days",
    vendor: "Appalachian Motive Power",
    vendorSince: "Verified since 2016",
    image: "/listings/power-assembly.jpg",
    featured: true,
    posted: "13 days ago",
    ageDays: 13,
    description: "Remanufactured 710G power assembly with measured component records. Injector type, piston configuration, and connecting-rod position are matched to the engine build.",
    keywords: ["710G", "power assembly", "piston", "liner", "cylinder", "SD70", "exchange"],
  },
  {
    id: 15,
    title: "EMD 645 Mechanical Unit Injector",
    category: "Engine Components",
    subcategory: "Fuel injection",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Rebuilt",
    region: "Mexico",
    location: "Monterrey, Nuevo León",
    quantity: 48,
    partNumber: "645-MUI",
    models: ["GP38", "GP40", "SD40-2"],
    engineFamily: "EMD 645",
    application: "Mechanical fuel injection",
    availability: "In stock",
    leadTime: "Ready to ship",
    vendor: "Norte Rail Diesel",
    vendorSince: "Verified since 2021",
    image: "/listings/warehouse.jpg",
    posted: "2 weeks ago",
    ageDays: 14,
    description: "Rebuilt mechanical unit injectors for EMD 645 applications, calibrated and flow-tested. Injector size and rack setting must match the engine configuration.",
    keywords: ["MUI", "unit injector", "645", "fuel system", "rack", "nozzle", "flow tested"],
  },
  {
    id: 16,
    title: "EMD 710 Electronic Unit Injector",
    category: "Engine Components",
    subcategory: "Fuel injection",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Remanufactured",
    region: "United States",
    location: "Fort Worth, Texas",
    quantity: 30,
    partNumber: "710-EUI",
    models: ["SD70ACe", "SD70M-2", "710G fleet"],
    engineFamily: "EMD 710G",
    application: "Electronic fuel injection",
    availability: "Core exchange",
    leadTime: "Exchange stock available",
    vendor: "Lone Star Fuel Systems",
    vendorSince: "Verified since 2018",
    image: "/listings/warehouse.jpg",
    posted: "15 days ago",
    ageDays: 15,
    description: "Remanufactured electronic unit injectors for compatible 710G engine builds. Units are bench-tested; calibration code and electrical connector must be confirmed.",
    keywords: ["EUI", "electronic injector", "710", "fuel system", "SD70ACe", "nozzle", "calibration"],
  },
  {
    id: 17,
    title: "EMD 645 / 710 Water Pump",
    category: "Engine Components",
    subcategory: "Engine pumps",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Rebuilt",
    region: "United States",
    location: "Paducah, Kentucky",
    quantity: 9,
    partNumber: "EMD-WATER-PUMP",
    models: ["645 fleet", "710 fleet", "GP / SD Series"],
    engineFamily: "EMD 645 / 710",
    application: "Engine coolant circulation",
    availability: "Core exchange",
    leadTime: "Ships in 3–5 business days",
    vendor: "River City Locomotive Supply",
    vendorSince: "Verified since 2012",
    image: "/listings/engine-blocks.jpg",
    posted: "16 days ago",
    ageDays: 16,
    description: "Rebuilt engine water pumps for selected EMD 645 and 710 configurations. Rotation, housing, and flange details are verified from the removed unit or engine serial.",
    keywords: ["water pump", "coolant pump", "645", "710", "cooling", "impeller", "exchange"],
  },
  {
    id: 18,
    title: "EMD 645 / 710 Lube Oil Pump",
    category: "Engine Components",
    subcategory: "Engine pumps",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Remanufactured",
    region: "United States",
    location: "Chicago, Illinois",
    quantity: 7,
    partNumber: "EMD-LUBE-PUMP",
    models: ["645 fleet", "710 fleet", "GP / SD Series"],
    engineFamily: "EMD 645 / 710",
    application: "Engine lubrication",
    availability: "Core exchange",
    leadTime: "Ships in 3–5 business days",
    vendor: "Midwest Rail Systems",
    vendorSince: "Verified since 2019",
    image: "/listings/engine-blocks.jpg",
    posted: "17 days ago",
    ageDays: 17,
    description: "Remanufactured lube oil pumps for selected 645 and 710 engine arrangements. Mounting, drive, and relief-valve configuration are confirmed before fulfillment.",
    keywords: ["lube oil pump", "lubrication", "645", "710", "gear pump", "oil pressure", "exchange"],
  },
  {
    id: 19,
    title: "GE 7FDL Cylinder Head",
    category: "Engine Components",
    subcategory: "Cylinder heads",
    manufacturer: "Wabtec / GE",
    builder: "GE",
    condition: "Remanufactured",
    region: "United States",
    location: "Waycross, Georgia",
    quantity: 20,
    partNumber: "7FDL-HEAD",
    models: ["Dash 8", "Dash 9", "AC4400CW"],
    engineFamily: "GE 7FDL12 / 7FDL16",
    application: "Cylinder head",
    availability: "In stock",
    leadTime: "Ships in 2–4 business days",
    vendor: "Coastal Rail Engine Works",
    vendorSince: "Verified since 2017",
    image: "/listings/power-assembly.jpg",
    posted: "18 days ago",
    ageDays: 18,
    description: "Remanufactured cylinder heads for GE 7FDL engine families, pressure-tested and measured. Valve and casting configuration are checked against the engine build.",
    keywords: ["FDL", "cylinder head", "Dash 8", "Dash 9", "valve", "pressure tested", "casting"],
  },
  {
    id: 20,
    title: "GEVO-12 Cylinder Head",
    category: "Engine Components",
    subcategory: "Cylinder heads",
    manufacturer: "Wabtec / GE",
    builder: "GE",
    condition: "Remanufactured",
    region: "Canada",
    location: "Hamilton, Ontario",
    quantity: 12,
    partNumber: "GEVO12-HEAD",
    models: ["ES44AC", "ES44DC", "ET44AC"],
    engineFamily: "GE Evolution Series",
    application: "Cylinder head",
    availability: "Lead time",
    leadTime: "2–3 weeks",
    vendor: "Ontario Heavy Rail",
    vendorSince: "Verified since 2020",
    image: "/listings/power-assembly.jpg",
    posted: "19 days ago",
    ageDays: 19,
    description: "Remanufactured cylinder head for GEVO-12 locomotive engines. Evolution Series variants are build-sensitive, so casting, valve train, and emissions configuration are verified.",
    keywords: ["GEVO", "GEVO12", "cylinder head", "Evolution Series", "ES44", "ET44", "valve train"],
  },

  // Traction motors — eight additional DC and AC motor families.
  {
    id: 21,
    title: "EMD D77 DC Traction Motor",
    category: "Traction Motors",
    subcategory: "DC traction motors",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Rebuilt",
    region: "United States",
    location: "Huntington, West Virginia",
    quantity: 8,
    partNumber: "EMD-D77",
    models: ["SD40-2", "GP40-2", "SD40-3"],
    engineFamily: "Not applicable",
    application: "Axle-mounted traction",
    availability: "Core exchange",
    leadTime: "Exchange stock available",
    vendor: "Allegheny Traction Service",
    vendorSince: "Verified since 2014",
    image: "/listings/traction-motor.jpg",
    featured: true,
    posted: "20 days ago",
    ageDays: 20,
    description: "Rebuilt EMD D77-family DC traction motor with electrical and mechanical test documentation. Pinion, axle diameter, and gear ratio are confirmed per application.",
    keywords: ["D77", "DC traction motor", "SD40-2", "armature", "pinion", "axle hung", "exchange"],
  },
  {
    id: 22,
    title: "EMD D87 DC Traction Motor",
    category: "Traction Motors",
    subcategory: "DC traction motors",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Rebuilt",
    region: "Canada",
    location: "Edmonton, Alberta",
    quantity: 5,
    partNumber: "EMD-D87",
    models: ["SD60", "SD70", "EMD DC fleet"],
    engineFamily: "Not applicable",
    application: "Axle-mounted traction",
    availability: "Core exchange",
    leadTime: "Exchange stock available",
    vendor: "Northline Components",
    vendorSince: "Verified since 2018",
    image: "/listings/traction-motor.jpg",
    posted: "21 days ago",
    ageDays: 21,
    description: "Rebuilt EMD D87-family DC traction motor for compatible road-locomotive applications. Gearcase, pinion, and wheelset interface are specified at order.",
    keywords: ["D87", "DC traction motor", "SD60", "SD70", "armature", "gearcase", "pinion"],
  },
  {
    id: 23,
    title: "EMD A2909 AC Traction Motor",
    category: "Traction Motors",
    subcategory: "AC traction motors",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Remanufactured",
    region: "United States",
    location: "Birmingham, Alabama",
    quantity: 3,
    partNumber: "EMD-A2909",
    models: ["SD70MAC", "EMD AC fleet"],
    engineFamily: "Not applicable",
    application: "AC axle traction",
    availability: "Lead time",
    leadTime: "3–4 weeks",
    vendor: "Southern Traction & Electric",
    vendorSince: "Verified since 2021",
    image: "/listings/traction-motor.jpg",
    posted: "22 days ago",
    ageDays: 22,
    description: "Remanufactured A2909-family AC traction motor. Final interchange depends on truck, gear ratio, inverter system, and locomotive build configuration.",
    keywords: ["A2909", "AC traction motor", "SD70MAC", "inverter", "three phase", "axle", "EMD"],
  },
  {
    id: 24,
    title: "EMD A3432 AC Traction Motor",
    category: "Traction Motors",
    subcategory: "AC traction motors",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Remanufactured",
    region: "Brazil",
    location: "Sete Lagoas, Minas Gerais",
    quantity: 4,
    partNumber: "EMD-A3432",
    models: ["SD70ACe", "EMD AC fleet"],
    engineFamily: "Not applicable",
    application: "AC axle traction",
    availability: "Core exchange",
    leadTime: "Exchange stock available",
    vendor: "Minas Rail Components",
    vendorSince: "Verified since 2019",
    image: "/listings/traction-motor.jpg",
    posted: "23 days ago",
    ageDays: 23,
    description: "Remanufactured A3432-family AC traction motor for selected EMD AC locomotive builds. Pinion, truck, and electrical configuration are validated before release.",
    keywords: ["A3432", "AC traction motor", "SD70ACe", "three phase", "pinion", "axle", "EMD"],
  },
  {
    id: 25,
    title: "GE 752AF DC Traction Motor",
    category: "Traction Motors",
    subcategory: "DC traction motors",
    manufacturer: "Wabtec / GE",
    builder: "GE",
    condition: "Rebuilt",
    region: "United States",
    location: "Cleveland, Ohio",
    quantity: 6,
    partNumber: "GE-752AF",
    models: ["C39-8", "C40-8", "GE DC fleet"],
    engineFamily: "Not applicable",
    application: "Axle-mounted traction",
    availability: "In stock",
    leadTime: "Ready to ship",
    vendor: "Lakefront Rotating Equipment",
    vendorSince: "Verified since 2016",
    image: "/listings/traction-motor.jpg",
    posted: "24 days ago",
    ageDays: 24,
    description: "Rebuilt 752AF-family DC traction motor with insulation, bearing, and no-load test records. Pinion and gearcase arrangement are selected for the receiving truck.",
    keywords: ["752AF", "GE 752", "DC traction motor", "Dash 8", "armature", "pinion", "axle hung"],
  },
  {
    id: 26,
    title: "GE 752E8 DC Traction Motor",
    category: "Traction Motors",
    subcategory: "DC traction motors",
    manufacturer: "Wabtec / GE",
    builder: "GE",
    condition: "Serviceable",
    region: "Mexico",
    location: "San Luis Potosí, San Luis Potosí",
    quantity: 7,
    partNumber: "GE-752E8",
    models: ["GE Dash 7 fleet", "GE Dash 8 fleet"],
    engineFamily: "Not applicable",
    application: "Axle-mounted traction",
    availability: "In stock",
    leadTime: "Ready for inspection",
    vendor: "Norte Rail Diesel",
    vendorSince: "Verified since 2021",
    image: "/listings/traction-motor.jpg",
    posted: "25 days ago",
    ageDays: 25,
    description: "Serviceable 752E8-family DC traction motors removed from operational locomotives. Electrical readings and mechanical inspection results are available for buyer review.",
    keywords: ["752E8", "GE 752", "DC motor", "Dash 7", "Dash 8", "traction", "take-out"],
  },
  {
    id: 27,
    title: "GE GEB13 AC Traction Motor",
    category: "Traction Motors",
    subcategory: "AC traction motors",
    manufacturer: "Wabtec / GE",
    builder: "GE",
    condition: "Remanufactured",
    region: "United States",
    location: "Fort Worth, Texas",
    quantity: 4,
    partNumber: "GE-GEB13",
    models: ["AC4400CW", "ES44AC", "GE AC fleet"],
    engineFamily: "Not applicable",
    application: "AC axle traction",
    availability: "Core exchange",
    leadTime: "Exchange stock available",
    vendor: "Gulf Coast Locomotive",
    vendorSince: "Verified since 2016",
    image: "/listings/traction-motor.jpg",
    featured: true,
    posted: "26 days ago",
    ageDays: 26,
    description: "Remanufactured GEB13-family AC traction motor for selected GE AC locomotive fleets. Build, gear ratio, axle, and inverter compatibility require confirmation.",
    keywords: ["GEB13", "AC traction motor", "AC4400CW", "ES44AC", "three phase", "axle", "inverter"],
  },
  {
    id: 28,
    title: "GE 761 DC Traction Motor",
    category: "Traction Motors",
    subcategory: "DC traction motors",
    manufacturer: "Wabtec / GE",
    builder: "GE",
    condition: "Rebuilt",
    region: "Brazil",
    location: "Contagem, Minas Gerais",
    quantity: 6,
    partNumber: "GE-761",
    models: ["GE U-Series", "GE DC fleet"],
    engineFamily: "Not applicable",
    application: "Axle-mounted traction",
    availability: "Lead time",
    leadTime: "2–3 weeks",
    vendor: "Minas Rail Components",
    vendorSince: "Verified since 2019",
    image: "/listings/traction-motor.jpg",
    posted: "27 days ago",
    ageDays: 27,
    description: "Rebuilt GE 761-family DC traction motor for legacy locomotive fleets. Motor suffix, pinion, gear ratio, and truck arrangement are verified per application.",
    keywords: ["GE 761", "DC traction motor", "U Series", "legacy fleet", "armature", "pinion", "truck"],
  },

  // Turbochargers — five additional engine-family listings.
  {
    id: 29,
    title: "EMD 645E3 Turbocharger Assembly",
    category: "Turbochargers",
    subcategory: "Complete turbochargers",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Remanufactured",
    region: "United States",
    location: "Chicago, Illinois",
    quantity: 3,
    partNumber: "645E3-TURBO",
    models: ["GP40", "SD40-2", "SD40T-2"],
    engineFamily: "EMD 645E3",
    application: "Engine air charging",
    availability: "Core exchange",
    leadTime: "Exchange stock available",
    vendor: "Midwest Rail Systems",
    vendorSince: "Verified since 2019",
    image: "/listings/turbocharger.jpg",
    featured: true,
    posted: "4 weeks ago",
    ageDays: 28,
    description: "Remanufactured turbocharger for selected 645E3 engine arrangements. Gear train, clutch, scroll, and exhaust configuration are matched to the engine build.",
    keywords: ["645E3", "turbocharger", "SD40-2", "GP40", "blower", "gear train", "exchange"],
  },
  {
    id: 30,
    title: "EMD 710G Turbocharger Assembly",
    category: "Turbochargers",
    subcategory: "Complete turbochargers",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Remanufactured",
    region: "Canada",
    location: "Calgary, Alberta",
    quantity: 2,
    partNumber: "710G-TURBO",
    models: ["SD70", "SD75", "GP60"],
    engineFamily: "EMD 710G",
    application: "Engine air charging",
    availability: "Core exchange",
    leadTime: "2–3 weeks",
    vendor: "Northline Components",
    vendorSince: "Verified since 2018",
    image: "/listings/turbocharger.jpg",
    posted: "29 days ago",
    ageDays: 29,
    description: "Remanufactured 710G-family turbocharger assembly with inspection and balance records. Exact engine model and turbocharger arrangement are required for interchange.",
    keywords: ["710G", "turbocharger", "SD70", "SD75", "GP60", "rotor", "air charging"],
  },
  {
    id: 31,
    title: "EMD 645 Turbo Clutch Assembly",
    category: "Turbochargers",
    subcategory: "Turbo drive components",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Rebuilt",
    region: "United States",
    location: "Altoona, Pennsylvania",
    quantity: 9,
    partNumber: "645-TURBO-CLUTCH",
    models: ["GP40", "SD40-2", "645 turbo fleet"],
    engineFamily: "EMD 645E3",
    application: "Turbocharger mechanical drive",
    availability: "Core exchange",
    leadTime: "Ships in 5–7 business days",
    vendor: "Keystone Diesel Works",
    vendorSince: "Verified since 2017",
    image: "/listings/turbocharger.jpg",
    posted: "30 days ago",
    ageDays: 30,
    description: "Rebuilt overrunning clutch assembly for compatible EMD 645 turbocharger gear trains. Rotation and turbo model are verified before shipment.",
    keywords: ["645", "turbo clutch", "overrunning clutch", "gear train", "GP40", "SD40-2", "turbo drive"],
  },
  {
    id: 32,
    title: "GE 7FDL Turbocharger Assembly",
    category: "Turbochargers",
    subcategory: "Complete turbochargers",
    manufacturer: "Wabtec / GE",
    builder: "GE",
    condition: "Remanufactured",
    region: "United States",
    location: "Houston, Texas",
    quantity: 4,
    partNumber: "7FDL-TURBO",
    models: ["Dash 8", "Dash 9", "AC4400CW"],
    engineFamily: "GE 7FDL12 / 7FDL16",
    application: "Engine air charging",
    availability: "Core exchange",
    leadTime: "Exchange stock available",
    vendor: "Gulf Coast Locomotive",
    vendorSince: "Verified since 2016",
    image: "/listings/turbocharger.jpg",
    posted: "31 days ago",
    ageDays: 31,
    description: "Remanufactured turbocharger for selected 7FDL12 and 7FDL16 engine builds. Inlet, exhaust, and engine configuration are confirmed by serial and locomotive model.",
    keywords: ["7FDL", "FDL12", "FDL16", "turbocharger", "Dash 8", "Dash 9", "AC4400CW"],
  },
  {
    id: 33,
    title: "GEVO-12 Turbocharger Cartridge",
    category: "Turbochargers",
    subcategory: "Turbo cartridges",
    manufacturer: "Wabtec / GE",
    builder: "GE",
    condition: "Remanufactured",
    region: "United States",
    location: "Erie, Pennsylvania",
    quantity: 3,
    partNumber: "GEVO12-TURBO-CHRA",
    models: ["ES44AC", "ES44DC", "ET44AC"],
    engineFamily: "GE Evolution Series",
    application: "Turbocharger rotating cartridge",
    availability: "Lead time",
    leadTime: "3–4 weeks",
    vendor: "Lake Erie Power Systems",
    vendorSince: "Verified since 2017",
    image: "/listings/turbocharger.jpg",
    posted: "32 days ago",
    ageDays: 32,
    description: "Remanufactured rotating cartridge for compatible GEVO-12 turbocharger assemblies. Turbo model and Evolution Series engine variant must be confirmed.",
    keywords: ["GEVO", "GEVO12", "turbo cartridge", "rotating group", "ES44", "ET44", "turbocharger"],
  },

  // Air and brake — seven additional control, compressor, and dryer listings.
  {
    id: 34,
    title: "NYAB CCB-26 EPCU Module",
    category: "Air & Brake",
    subcategory: "Electronic brake control",
    manufacturer: "New York Air Brake",
    builder: "Multi-platform",
    condition: "Remanufactured",
    region: "United States",
    location: "Elkhart, Indiana",
    quantity: 5,
    partNumber: "CCB-26-EPCU",
    models: ["CCB-26 equipped fleet", "Modern road locomotives"],
    engineFamily: "Not applicable",
    application: "Electro-pneumatic brake control",
    availability: "Core exchange",
    leadTime: "Exchange stock available",
    vendor: "Great Lakes Rail Supply",
    vendorSince: "Verified since 2020",
    image: "/listings/warehouse.jpg",
    featured: true,
    posted: "33 days ago",
    ageDays: 33,
    description: "Remanufactured electro-pneumatic control unit for CCB-26 locomotive brake systems. Software, LRU configuration, and brake schedule require build-level confirmation.",
    keywords: ["CCB26", "CCB-26", "EPCU", "electronic air brake", "NYAB", "brake control", "LRU"],
  },
  {
    id: 35,
    title: "NYAB CCB-26 Electronic Brake Valve",
    category: "Air & Brake",
    subcategory: "Electronic brake control",
    manufacturer: "New York Air Brake",
    builder: "Multi-platform",
    condition: "Remanufactured",
    region: "United States",
    location: "Roanoke, Virginia",
    quantity: 4,
    partNumber: "CCB-26-EBV",
    models: ["CCB-26 equipped fleet", "26C-envelope retrofit"],
    engineFamily: "Not applicable",
    application: "Engineer brake command",
    availability: "Core exchange",
    leadTime: "2–3 weeks",
    vendor: "Appalachian Motive Power",
    vendorSince: "Verified since 2016",
    image: "/listings/warehouse.jpg",
    posted: "34 days ago",
    ageDays: 34,
    description: "Remanufactured electronic brake valve for CCB-26 systems. The EBV uses the 26C mounting envelope; controls and system version still require confirmation.",
    keywords: ["CCB26", "EBV", "electronic brake valve", "26C", "NYAB", "automatic brake", "independent brake"],
  },
  {
    id: 36,
    title: "26L Independent Brake Valve",
    category: "Air & Brake",
    subcategory: "Brake control valves",
    manufacturer: "New York Air Brake",
    builder: "Multi-platform",
    condition: "Rebuilt",
    region: "United States",
    location: "Kansas City, Missouri",
    quantity: 10,
    partNumber: "26L-INDEPENDENT",
    models: ["GP Series", "SD Series", "26L equipped fleet"],
    engineFamily: "Not applicable",
    application: "Locomotive-only brake control",
    availability: "Core exchange",
    leadTime: "Ready to ship",
    vendor: "Central States Diesel",
    vendorSince: "Verified since 2014",
    image: "/listings/warehouse.jpg",
    posted: "35 days ago",
    ageDays: 35,
    description: "Rebuilt independent brake valve for 26L locomotive brake stands. Handle, porting, and bail-off arrangement are verified against the original valve.",
    keywords: ["26L", "independent brake", "bail off", "brake stand", "air brake", "locomotive brake", "valve"],
  },
  {
    id: 37,
    title: "Wabtec 3CW Water-Cooled Compressor",
    category: "Air & Brake",
    subcategory: "Air compressors",
    manufacturer: "Wabtec",
    builder: "Multi-platform",
    condition: "Remanufactured",
    region: "United States",
    location: "Fort Worth, Texas",
    quantity: 3,
    partNumber: "3CW",
    models: ["Road locomotives", "Water-cooled air systems"],
    engineFamily: "Not applicable",
    application: "Locomotive compressed-air supply",
    availability: "Core exchange",
    leadTime: "3–4 weeks",
    vendor: "Lone Star Air & Brake",
    vendorSince: "Verified since 2018",
    image: "/listings/engine-blocks.jpg",
    posted: "36 days ago",
    ageDays: 36,
    description: "Remanufactured Wabtec 3CW three-cylinder, water-cooled air compressor for locomotive air systems. Drive and plumbing configuration are confirmed per installation.",
    keywords: ["3CW", "air compressor", "three cylinder", "water cooled", "main reservoir", "air generation", "Wabtec"],
  },
  {
    id: 38,
    title: "Wabtec AirSmart 994-600 Air Dryer",
    category: "Air & Brake",
    subcategory: "Air dryers",
    manufacturer: "Wabtec",
    builder: "Multi-platform",
    condition: "New Surplus",
    region: "United States",
    location: "Cleveland, Ohio",
    quantity: 6,
    partNumber: "994-600",
    models: ["High-horsepower road fleet", "Locomotive air systems"],
    engineFamily: "Not applicable",
    application: "Compressed-air drying",
    availability: "In stock",
    leadTime: "Ready to ship",
    vendor: "Lakefront Rotating Equipment",
    vendorSince: "Verified since 2016",
    image: "/listings/warehouse.jpg",
    posted: "37 days ago",
    ageDays: 37,
    description: "New-surplus AirSmart 994-600 locomotive air dryer. Installation kit, voltage, piping, and controller compatibility should be confirmed for the receiving unit.",
    keywords: ["994-600", "AirSmart", "air dryer", "desiccant", "compressed air", "moisture", "Wabtec"],
  },
  {
    id: 39,
    title: "Wabtec AirSmart 994-500 Air Dryer",
    category: "Air & Brake",
    subcategory: "Air dryers",
    manufacturer: "Wabtec",
    builder: "Multi-platform",
    condition: "New",
    region: "Canada",
    location: "Hamilton, Ontario",
    quantity: 4,
    partNumber: "994-500",
    models: ["3,000–4,000 hp fleet", "Locomotive air systems"],
    engineFamily: "Not applicable",
    application: "Compressed-air drying",
    availability: "Lead time",
    leadTime: "2–3 weeks",
    vendor: "Ontario Heavy Rail",
    vendorSince: "Verified since 2020",
    image: "/listings/warehouse.jpg",
    posted: "38 days ago",
    ageDays: 38,
    description: "AirSmart 994-500 air dryer for typical 3,000–4,000 horsepower locomotive applications. Voltage, piping, and installation arrangement are verified at order.",
    keywords: ["994-500", "AirSmart", "air dryer", "desiccant", "3000 hp", "4000 hp", "Wabtec"],
  },
  {
    id: 40,
    title: "Wabtec Twin Tower 975 Air Dryer",
    category: "Air & Brake",
    subcategory: "Air dryers",
    manufacturer: "Wabtec",
    builder: "Multi-platform",
    condition: "Remanufactured",
    region: "United States",
    location: "Elkhart, Indiana",
    quantity: 5,
    partNumber: "975-SERIES",
    models: ["Legacy road fleet", "Locomotive air systems"],
    engineFamily: "Not applicable",
    application: "Compressed-air drying",
    availability: "Core exchange",
    leadTime: "Exchange stock available",
    vendor: "Great Lakes Rail Supply",
    vendorSince: "Verified since 2020",
    image: "/listings/warehouse.jpg",
    posted: "39 days ago",
    ageDays: 39,
    description: "Remanufactured Twin Tower 975-series locomotive air dryer. Tower, purge, heater, and control arrangement are verified from the existing installation.",
    keywords: ["975", "Twin Tower", "air dryer", "desiccant", "purge valve", "compressed air", "Wabtec"],
  },

  // Electrical — seven additional rotating-machine and accessory-drive listings.
  {
    id: 41,
    title: "EMD AR10 Traction Alternator",
    category: "Electrical",
    subcategory: "Traction alternators",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Remanufactured",
    region: "United States",
    location: "Birmingham, Alabama",
    quantity: 2,
    partNumber: "EMD-AR10",
    models: ["GP38-2", "GP40-2", "SD40-2"],
    engineFamily: "EMD 645",
    application: "Main traction power generation",
    availability: "Core exchange",
    leadTime: "3–5 weeks",
    vendor: "Southern Traction & Electric",
    vendorSince: "Verified since 2021",
    image: "/listings/traction-motor.jpg",
    featured: true,
    posted: "40 days ago",
    ageDays: 40,
    description: "Remanufactured AR10-family traction alternator for compatible EMD DC locomotives. Companion alternator, excitation, and mounting configuration are confirmed per build.",
    keywords: ["AR10", "traction alternator", "main generator", "SD40-2", "GP40-2", "rotating equipment", "EMD"],
  },
  {
    id: 42,
    title: "EMD CA6 Companion Alternator",
    category: "Electrical",
    subcategory: "Companion alternators",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Rebuilt",
    region: "United States",
    location: "Huntington, West Virginia",
    quantity: 4,
    partNumber: "EMD-CA6",
    models: ["AR10-equipped EMD fleet", "710ECO package"],
    engineFamily: "EMD 645 / 710",
    application: "Auxiliary electrical generation",
    availability: "Core exchange",
    leadTime: "2–3 weeks",
    vendor: "Allegheny Traction Service",
    vendorSince: "Verified since 2014",
    image: "/listings/traction-motor.jpg",
    posted: "41 days ago",
    ageDays: 41,
    description: "Rebuilt CA6-family companion alternator for compatible EMD main-alternator packages. Drive, excitation, and electrical configuration must match the locomotive.",
    keywords: ["CA6", "companion alternator", "auxiliary generator", "AR10", "710ECO", "EMD", "excitation"],
  },
  {
    id: 43,
    title: "50MT Locomotive Starter Motor",
    category: "Electrical",
    subcategory: "Starter motors",
    manufacturer: "Multi-OEM",
    builder: "Multi-platform",
    condition: "Remanufactured",
    region: "United States",
    location: "Paducah, Kentucky",
    quantity: 16,
    partNumber: "50MT",
    models: ["EMD 645 fleet", "EMD 710 fleet", "Industrial diesel"],
    engineFamily: "EMD 645 / 710",
    application: "Engine starting",
    availability: "In stock",
    leadTime: "Ready to ship",
    vendor: "River City Locomotive Supply",
    vendorSince: "Verified since 2012",
    image: "/listings/warehouse.jpg",
    posted: "42 days ago",
    ageDays: 42,
    description: "Remanufactured 50MT-family electric starter motor for compatible locomotive and industrial diesel installations. Voltage, rotation, drive, and mounting are verified.",
    keywords: ["50MT", "starter motor", "cranking motor", "EMD 645", "EMD 710", "electric start", "24 volt"],
  },
  {
    id: 44,
    title: "GE GMG186 Traction Alternator",
    category: "Electrical",
    subcategory: "Traction alternators",
    manufacturer: "Wabtec / GE",
    builder: "GE",
    condition: "Rebuildable Core",
    region: "United States",
    location: "Houston, Texas",
    quantity: 2,
    partNumber: "GMG186",
    models: ["Dash 8 family", "GE FDL fleet"],
    engineFamily: "GE 7FDL",
    application: "Main traction power generation",
    availability: "In stock",
    leadTime: "Ready for inspection",
    vendor: "Gulf Coast Locomotive",
    vendorSince: "Verified since 2016",
    image: "/listings/traction-motor.jpg",
    posted: "43 days ago",
    ageDays: 43,
    description: "GMG186-family traction alternator core for compatible GE FDL locomotive applications. Shaft, mounting, and excitation configuration are documented for rebuild planning.",
    keywords: ["GMG186", "traction alternator", "main generator", "Dash 8", "GE FDL", "core", "rotating equipment"],
  },
  {
    id: 45,
    title: "GE GMG187 Traction Alternator",
    category: "Electrical",
    subcategory: "Traction alternators",
    manufacturer: "Wabtec / GE",
    builder: "GE",
    condition: "Remanufactured",
    region: "United States",
    location: "Cleveland, Ohio",
    quantity: 2,
    partNumber: "GMG187",
    models: ["Dash 9 family", "GE FDL fleet"],
    engineFamily: "GE 7FDL",
    application: "Main traction power generation",
    availability: "Core exchange",
    leadTime: "3–5 weeks",
    vendor: "Lakefront Rotating Equipment",
    vendorSince: "Verified since 2016",
    image: "/listings/traction-motor.jpg",
    posted: "44 days ago",
    ageDays: 44,
    description: "Remanufactured GMG187-family traction alternator with electrical and mechanical test documentation. Exact FDL application and excitation package are confirmed by build.",
    keywords: ["GMG187", "traction alternator", "main generator", "Dash 9", "GE FDL", "excitation", "exchange"],
  },
  {
    id: 46,
    title: "GE GDY75C Traction Motor Blower",
    category: "Electrical",
    subcategory: "Blower motors",
    manufacturer: "Wabtec / GE",
    builder: "GE",
    condition: "Rebuilt",
    region: "Canada",
    location: "Winnipeg, Manitoba",
    quantity: 5,
    partNumber: "GDY75C",
    models: ["Dash 8", "Dash 9", "GE road fleet"],
    engineFamily: "Not applicable",
    application: "Traction motor cooling airflow",
    availability: "In stock",
    leadTime: "Ready to ship",
    vendor: "Prairie Rail Rebuilders",
    vendorSince: "Verified since 2016",
    image: "/listings/warehouse.jpg",
    posted: "45 days ago",
    ageDays: 45,
    description: "Rebuilt GDY75C-family traction motor blower for selected GE Dash 8 and Dash 9 locomotive builds. Rotation, voltage, and duct arrangement are verified.",
    keywords: ["GDY75C", "traction motor blower", "blower motor", "Dash 8", "Dash 9", "cooling air", "GE"],
  },
  {
    id: 47,
    title: "GE GYA30A Radiator Fan Motor",
    category: "Electrical",
    subcategory: "Fan motors",
    manufacturer: "Wabtec / GE",
    builder: "GE",
    condition: "Rebuilt",
    region: "United States",
    location: "Waycross, Georgia",
    quantity: 6,
    partNumber: "GYA30A",
    models: ["Dash 8", "Dash 9", "GE road fleet"],
    engineFamily: "GE 7FDL",
    application: "Radiator fan drive",
    availability: "Core exchange",
    leadTime: "2–3 weeks",
    vendor: "Coastal Rail Engine Works",
    vendorSince: "Verified since 2017",
    image: "/listings/warehouse.jpg",
    posted: "46 days ago",
    ageDays: 46,
    description: "Rebuilt GYA30A-family radiator fan motor for compatible GE locomotive cooling systems. Electrical rating, rotation, and fan arrangement are matched to the unit.",
    keywords: ["GYA30A", "radiator fan motor", "cooling fan", "Dash 8", "Dash 9", "GE", "radiator"],
  },

  // Cooling and lubrication — five additional heat-exchanger listings.
  {
    id: 48,
    title: "GE 7FDL Radiator Section",
    category: "Cooling & Lube",
    subcategory: "Radiators",
    manufacturer: "Wabtec / GE",
    builder: "GE",
    condition: "New",
    region: "United States",
    location: "Erie, Pennsylvania",
    quantity: 14,
    partNumber: "7FDL-RADIATOR",
    models: ["Dash 8", "Dash 9", "AC4400CW"],
    engineFamily: "GE 7FDL12 / 7FDL16",
    application: "Engine coolant heat rejection",
    availability: "In stock",
    leadTime: "Ships in 3–5 business days",
    vendor: "Lake Erie Power Systems",
    vendorSince: "Verified since 2017",
    image: "/listings/warehouse.jpg",
    featured: true,
    posted: "47 days ago",
    ageDays: 47,
    description: "Replacement radiator section for selected GE FDL locomotive cooling packages. Core dimensions, header arrangement, and pressure specification are confirmed per model.",
    keywords: ["FDL radiator", "radiator core", "Dash 8", "Dash 9", "AC4400CW", "cooling system", "heat exchanger"],
  },
  {
    id: 49,
    title: "GEVO Advanced-Cooling Radiator Section",
    category: "Cooling & Lube",
    subcategory: "Radiators",
    manufacturer: "Wabtec / GE",
    builder: "GE",
    condition: "New",
    region: "Canada",
    location: "Hamilton, Ontario",
    quantity: 8,
    partNumber: "GEVO-RADIATOR",
    models: ["ES44AC", "ES44DC", "ET44AC"],
    engineFamily: "GE Evolution Series",
    application: "Engine coolant heat rejection",
    availability: "Lead time",
    leadTime: "3–4 weeks",
    vendor: "Ontario Heavy Rail",
    vendorSince: "Verified since 2020",
    image: "/listings/warehouse.jpg",
    posted: "48 days ago",
    ageDays: 48,
    description: "Radiator section for compatible Evolution Series locomotive cooling packages. ET44 advanced-cooling applications require build-specific section and header confirmation.",
    keywords: ["GEVO radiator", "Evolution Series", "ES44AC", "ET44AC", "advanced cooling", "radiator core", "heat exchanger"],
  },
  {
    id: 50,
    title: "EMD 645 Engine Aftercooler",
    category: "Cooling & Lube",
    subcategory: "Aftercoolers",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Remanufactured",
    region: "United States",
    location: "Muncie, Indiana",
    quantity: 5,
    partNumber: "645-AFTERCOOLER",
    models: ["GP40", "SD40-2", "645 turbo fleet"],
    engineFamily: "EMD 645E3",
    application: "Charge-air cooling",
    availability: "Core exchange",
    leadTime: "2–3 weeks",
    vendor: "Heartland Repower Services",
    vendorSince: "Verified since 2018",
    image: "/listings/engine-blocks.jpg",
    posted: "49 days ago",
    ageDays: 49,
    description: "Remanufactured aftercooler for compatible turbocharged EMD 645 engine arrangements. Core, header, and plumbing details are matched to the engine build.",
    keywords: ["645", "aftercooler", "charge air cooler", "intercooler", "GP40", "SD40-2", "heat exchanger"],
  },
  {
    id: 51,
    title: "EMD 710 Separate-Loop Aftercooler",
    category: "Cooling & Lube",
    subcategory: "Aftercoolers",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Remanufactured",
    region: "United States",
    location: "Tacoma, Washington",
    quantity: 3,
    partNumber: "710-SLAC",
    models: ["710ECO repower", "SD70ACe", "710G fleet"],
    engineFamily: "EMD 710G",
    application: "Separate-loop charge-air cooling",
    availability: "Lead time",
    leadTime: "3–5 weeks",
    vendor: "Cascade Locomotive Works",
    vendorSince: "Verified since 2015",
    image: "/listings/engine-blocks.jpg",
    posted: "50 days ago",
    ageDays: 50,
    description: "Remanufactured aftercooler for selected EMD 710 separate-loop systems, including repower applications. Plumbing and cooling-circuit configuration are verified.",
    keywords: ["710", "separate loop", "aftercooler", "charge air cooler", "710ECO", "SD70ACe", "heat exchanger"],
  },
  {
    id: 52,
    title: "Locomotive Lube Oil Cooler",
    category: "Cooling & Lube",
    subcategory: "Oil coolers",
    manufacturer: "Multi-OEM",
    builder: "Multi-platform",
    condition: "Remanufactured",
    region: "Mexico",
    location: "Monterrey, Nuevo León",
    quantity: 7,
    partNumber: "LOCO-LUBE-COOLER",
    models: ["EMD 645 fleet", "EMD 710 fleet", "GE FDL fleet"],
    engineFamily: "Multiple engine families",
    application: "Lube-oil heat rejection",
    availability: "Made to order",
    leadTime: "2–4 weeks from sample or drawing",
    vendor: "Norte Rail Diesel",
    vendorSince: "Verified since 2021",
    image: "/listings/engine-blocks.jpg",
    posted: "51 days ago",
    ageDays: 51,
    description: "Remanufactured or built-to-sample lube oil cooler for locomotive diesel applications. Core dimensions, flow arrangement, materials, and pressure test are application-specific.",
    keywords: ["lube oil cooler", "oil cooler", "heat exchanger", "645", "710", "FDL", "lubrication"],
  },

  // Running gear — four additional truck, wheel, and draft-system listings.
  {
    id: 53,
    title: "EMD Blomberg M Truck Assembly",
    category: "Running Gear",
    subcategory: "Truck assemblies",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Rebuilt",
    region: "United States",
    location: "Kansas City, Missouri",
    quantity: 2,
    partNumber: "BLOMBERG-M",
    models: ["GP38", "GP40", "GP Series"],
    engineFamily: "Not applicable",
    application: "Two-axle locomotive truck",
    availability: "Core exchange",
    leadTime: "4–6 weeks",
    vendor: "Central States Diesel",
    vendorSince: "Verified since 2014",
    image: "/listings/traction-motor.jpg",
    featured: true,
    posted: "52 days ago",
    ageDays: 52,
    description: "Rebuilt Blomberg M two-axle truck assembly for compatible EMD GP locomotives. Gear ratio, traction motors, brake rigging, and wheel profile are specified at order.",
    keywords: ["Blomberg M", "truck assembly", "bogie", "GP38", "GP40", "wheelset", "brake rigging"],
  },
  {
    id: 54,
    title: "EMD HT-C Three-Axle Truck Assembly",
    category: "Running Gear",
    subcategory: "Truck assemblies",
    manufacturer: "Progress Rail / EMD",
    builder: "EMD",
    condition: "Rebuilt",
    region: "United States",
    location: "Roanoke, Virginia",
    quantity: 2,
    partNumber: "EMD-HTC-TRUCK",
    models: ["SD40-2", "SD50", "SD60"],
    engineFamily: "Not applicable",
    application: "Three-axle locomotive truck",
    availability: "Made to order",
    leadTime: "6–8 weeks",
    vendor: "Appalachian Motive Power",
    vendorSince: "Verified since 2016",
    image: "/listings/traction-motor.jpg",
    posted: "53 days ago",
    ageDays: 53,
    description: "Rebuilt HT-C-family three-axle truck for selected EMD SD locomotives. Traction motor type, gear ratio, brake equipment, and wheel profile are build-specific.",
    keywords: ["HT-C", "HTC truck", "truck assembly", "bogie", "SD40-2", "SD60", "three axle"],
  },
  {
    id: 55,
    title: "Locomotive Wheelset & Axle Assembly",
    category: "Running Gear",
    subcategory: "Wheelsets",
    manufacturer: "Multi-OEM",
    builder: "Multi-platform",
    condition: "Requalified",
    region: "United States",
    location: "Altoona, Pennsylvania",
    quantity: 12,
    partNumber: "LOCO-WHEELSET",
    models: ["EMD road fleet", "GE road fleet", "Industrial locomotives"],
    engineFamily: "Not applicable",
    application: "Locomotive running gear",
    availability: "Made to order",
    leadTime: "4–6 weeks",
    vendor: "Keystone Diesel Works",
    vendorSince: "Verified since 2017",
    image: "/listings/warehouse.jpg",
    posted: "54 days ago",
    ageDays: 54,
    description: "Requalified or assembled locomotive wheelset and axle combinations. Axle drawing, wheel profile, bearing seats, gear, and traction motor interface are required.",
    keywords: ["wheelset", "axle", "locomotive wheel", "gear", "bearing seat", "running gear", "requalified"],
  },
  {
    id: 56,
    title: "Locomotive Draft Gear for E / F / H Couplers",
    category: "Running Gear",
    subcategory: "Draft systems",
    manufacturer: "Wabtec",
    builder: "Multi-platform",
    condition: "New",
    region: "United States",
    location: "Chicago, Illinois",
    quantity: 8,
    partNumber: "LOCO-DRAFT-GEAR",
    models: ["Freight locomotives", "E / F / H coupler systems"],
    engineFamily: "Not applicable",
    application: "Longitudinal impact energy management",
    availability: "Lead time",
    leadTime: "2–4 weeks",
    vendor: "Midwest Rail Systems",
    vendorSince: "Verified since 2019",
    image: "/listings/warehouse.jpg",
    posted: "55 days ago",
    ageDays: 55,
    description: "Locomotive draft gear for compatible E-, F-, or H-type coupler systems. Pocket dimensions, yoke, follower, travel, and service requirements must be confirmed.",
    keywords: ["draft gear", "coupler", "E coupler", "F coupler", "H coupler", "draft system", "energy absorption"],
  },
];
